-- Run once in the Supabase SQL Editor before deploying employee upgrades.
create table if not exists public.employee_compensation_history (
    id bigint generated by default as identity primary key,
    employee_id bigint not null references public.employees(id) on delete cascade,
    effective_from date not null,
    designation text not null,
    salary numeric(12,2) not null check (salary >= 0),
    changed_by bigint references public.employees(id),
    created_at timestamptz not null default now(),
    unique(employee_id, effective_from)
);

insert into public.employee_compensation_history (
    employee_id, effective_from, designation, salary
)
select id, joining_date,
       coalesce(nullif(designation, ''), 'Employee'), coalesce(salary, 0)
from public.employees
on conflict (employee_id, effective_from) do nothing;

alter table public.salary_slips
add column if not exists designation text,
add column if not exists compensation_details jsonb not null default '[]'::jsonb;

update public.salary_slips s
set designation = coalesce(nullif(e.designation, ''), 'Employee')
from public.employees e
where s.employee_id = e.id and s.designation is null;

alter table public.salary_slips
alter column designation set not null;
