-- Run once in the Supabase SQL Editor.
create table if not exists public.salary_slips (
    id bigint generated by default as identity primary key,
    employee_id bigint not null references public.employees(id),
    payroll_month date not null,
    gross_salary numeric(12,2) not null,
    working_days integer not null,
    present_days integer not null,
    cl_days integer not null default 0,
    sl_days integer not null default 0,
    paid_leave_days integer not null default 0,
    half_days integer not null default 0,
    unpaid_days numeric(6,2) not null default 0,
    deduction numeric(12,2) not null default 0,
    net_salary numeric(12,2) not null,
    leave_details jsonb not null default '[]'::jsonb,
    generated_by bigint references public.employees(id),
    generated_at timestamptz not null default now(),
    unique(employee_id, payroll_month)
);

create index if not exists salary_slips_employee_month_idx
on public.salary_slips(employee_id, payroll_month desc);
